### ISSUE TITLE
Password 

### ISSUE THREAD

**Issue by Srgadget** [songzh96/node-red-contrib-crestron#15]
Was wondering if you might like to share the Crestron source as I wanted to add a feature or two. 1) digital output to show the connection.  2) Digital to show activity. 3) May be even a debug serial string. I do all my work in 2 and 3 series units as I mostly do lighting systems....  Thank you very much in advance and have a  great day.

**Comment by Pugy365** [comment]
Also looking for the password, I am currently using this and have an issue where the TCP connection stops working until I access the crestron processor directly with telnet and then everything works again for a bit.

**Comment by songzh96** [comment]
Yes, there are currently some bugs with this plugin. Since I am working on KNX now, this plugin is rarely maintained. Currently you can use another plugin homebridge-crestron to achieve your needs, which is more stable


Songzh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songzh96/node-red-contrib-crestron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月31日(星期六) 晚上10:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [songzh96/node-red-contrib-crestron] Password  (Issue #15)





 
Also looking for the password, I am currently using this and have an issue where the TCP connection stops working until I access the crestron processor directly with telnet and then everything works again for a bit.

**Comment by Srgadget** [comment]
That sound like a creston issue .. which processor and firmware are you on?Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Pugy365 ***@***.***> Date: 12/31/22  8:17 AM  (GMT-06:00) To: songzh96/node-red-contrib-crestron ***@***.***> Cc: Srgadget ***@***.***>, Author ***@***.***> Subject: Re: [songzh96/node-red-contrib-crestron] Password  (Issue #15) 
Also looking for the password, I am currently using this and have an issue where the TCP connection stops working until I access the crestron processor directly with telnet and then everything works again for a bit.

**Comment by songzh96** [comment]
DIN-AP3，I forget the firmware


Songzh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "songzh96/node-red-contrib-crestron"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月1日(星期天) 凌晨1:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [songzh96/node-red-contrib-crestron] Password  (Issue #15)





 That sound like a creston issue .. which processor and firmware are you on?Sent from my Verizon, Samsung Galaxy smartphone
 -------- Original message --------From: Pugy365 ***@***.***&gt; Date: 12/31/22  8:17 AM  (GMT-06:00) To: songzh96/node-red-contrib-crestron ***@***.***&gt; Cc: Srgadget ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [songzh96/node-red-contrib-crestron] Password  (Issue #15) 
 Also looking for the password, I am currently using this and have an issue where the TCP connection stops working until I access the crestron processor directly with telnet and then everything works again for a bit.

**Comment by Srgadget** [comment]
I will see If I can recreate the issue I am running in on some pack2 mini's
no issues for over 6 months.

**Comment by galaye** [comment]
there is still an issue ,tried several processor with lates fw...
if u will share the password i will try to get arround it
